// src/brands/straunt/environment.ts
import type { BrandEnvironment } from '../types';

// Straunt brand auth constants — per-brand tenant identifiers.
// These differ per brand and MUST NOT be mixed up: using Holiq's appGroupId
// with Straunt credentials (or vice-versa) will cause subscription mismatches.
const STRAUNT_AUTH = {
  appGroupId:        '1719308705812195',
  prdId:             '1718865526155464',
  storesServiceId:   '3821548006039960',
  channelsServiceId: '3880470537073453',
  uniqueCode:        'straunt',
} as const;

export const strauntEnvironment: BrandEnvironment = {
  brandId: 'straunt',
  displayName: import.meta.env.VITE_DISPLAY_NAME || '',
  appId: 'com.straunt.kiosk',
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || 'https://api.straunt.com/v1',
  apiKey: import.meta.env.VITE_API_KEY || '',
  brandHeader: import.meta.env.VITE_BRAND_HEADER || 'straunt',
  defaultTheme: {
    primary:      '#F97316',
    secondary:    '#EA580C',
    accent:       '#F97316',
    background:   '#FFF8F0',
    surface:      '#FFF3E8',
    surfaceAlt:   '#FFE8D0',
    text:         '#1C1917',
    textMuted:    '#78716C',
    textInverse:  '#FFFFFF',
    border:       '#E7E0D9',
    error:        '#EF4444',
    success:      '#22C55E',
    warning:      '#F59E0B',
    fontFamily:   "'Inter', system-ui, sans-serif",
    logoUrl:      '',
    radius:       '0.75rem',
    primaryHover:  '#EA580C',
    primaryActive: '#C2410C',
    gradientStart: '#F97316',
    gradientEnd:   '#EA580C',
    badgeBg:       'rgba(249,115,22,0.10)',
  },
  catalog: {
    strategy: 'full-load',
    defaultSortOrder: 'api-order',
    productCardVariant: 'standard',
    showDietaryBadges: true,
    hideUnavailableProducts: false,
    excludedCategoryIds: [],
  },
  authConfig: STRAUNT_AUTH,

  defaultTaxRate: 0.0825,
  defaultLocale: 'en-US',
  defaultCurrency: 'USD',
  defaultTimezone: 'America/Chicago',

  businessRules: {
    ageVerification: {
      enabled: false,
      minAge: 18,
      prompt: 'You must be {minAge} or older to order from this section.',
      subtitle: 'Please confirm your age to continue.',
    },
    dietary: {
      showCalories: true,
      badges: {
        isVeg:        { label: 'V',  name: 'Vegetarian',  color: '#16A34A' },
        isVegan:      { label: 'VE', name: 'Vegan',        color: '#15803D' },
        isGlutenFree: { label: 'GF', name: 'Gluten-Free',  color: '#7C3AED' },
        isNutFree:    { label: 'NF', name: 'Nut-Free',     color: '#0891B2' },
        isSpicy:      { label: '🌶', name: 'Spicy',         color: '#DC2626' },
      },
    },
    tipConfig: {
      enabled: true,
      presets: [15, 18, 20],
      customAllowed: true,
      defaultPercent: undefined,
    },
    receiptConfig: {
      logoOnReceipt: true,
      footerMessage: 'Thank you for dining with us!',
      showTaxBreakdown: true,
      printEnabled: true,
      autoReturnSeconds: 30,
    },
    orderFlowConfig: {
      dineInEnabled: true,
      takeoutEnabled: true,
      askOrderType: false,
      defaultOrderType: 'takeout',
    },
    loyaltyConfig: {
      enabled: false,
      programName: 'Straunt Rewards',
      lookupMethod: 'phone',
    },
    upsellConfig: {
      enabled: true,
      triggerStage: 'cart',
      maxSuggestions: 3,
    },
    supportedPaymentMethods: ['card'],
    kioskDefaults: {
      idleTimeoutSeconds: 120,
      attractLoopEnabled: true,
      staffPinEnabled: true,
    },
  },

  attractScreen: {
    idleVideoUrl: undefined,
    idleImageUrls: [],
    tagline: 'Order.',
    taglineHighlight: 'Here.',
    ctaLabel: 'Tap to Order',
    showLogo: true,
    featureBadges: ['Order at your pace', 'Customize freely', 'Pay securely'],
    heroLayout: 'split-headline',
    doodles: ['🍔','🍕','🌮','🥗','🍟','🍜','🥩','🍰','☕','🥤','🍣','🫔'],
  },

  categoryIconMap: {
    'burger':    '🍔',
    'sandwich':  '🥪',
    'chicken':   '🍗',
    'wing':      '🍗',
    'bowl':      '🥗',
    'rice':      '🍚',
    'biryani':   '🍚',
    'side':      '🍟',
    'frie':      '🍟',
    'appetizer': '🥟',
    'drink':     '🥤',
    'beverage':  '🥤',
    'juice':     '🍹',
    'dessert':   '🍰',
    'sweet':     '🧁',
    'cake':      '🎂',
    'pizza':     '🍕',
    'flatbread': '🫓',
    'salad':     '🥦',
    'veggie':    '🥗',
    'coffee':    '☕',
    'tea':       '🫖',
    'combo':     '🍱',
    'meal':      '🍱',
    'special':   '⭐',
    'soup':      '🍲',
    'wrap':      '🌯',
    'taco':      '🌮',
    'burrito':   '🌯',
    'seafood':   '🦐',
    'fish':      '🐟',
    'shrimp':    '🍤',
    'steak':     '🥩',
    'beef':      '🥩',
    'meat':      '🍖',
    'pasta':     '🍝',
    'noodle':    '🍜',
    'bread':     '🫓',
    'roti':      '🫓',
    'naan':      '🫓',
    'breakfast': '🍳',
    'morning':   '🍳',
    'snack':     '🍿',
    'bite':      '🧆',
    'dosa':      '🥞',
    'curry':     '🍛',
  },

  altPayment: {
    // Industry ID for Straunt — sent as `industry_id` in phone-pay API calls.
    // Override with VITE_STRAUNT_INDUSTRY_ID in your .env file.
    industryId:           import.meta.env.VITE_STRAUNT_INDUSTRY_ID           || '',
    // Default / anonymous customer used for QR-Pay cart creation.
    defaultCustomerId:    import.meta.env.VITE_STRAUNT_DEFAULT_CUSTOMER_ID   || '',
    defaultCustomerPhone: import.meta.env.VITE_STRAUNT_DEFAULT_PHONE         || '0000000000',
    // Base URL for the anonymous cart viewer (QR code destination).
    anonymousProjectUrl:  import.meta.env.VITE_ANONYMOUS_PROJECT_URL         || 'https://straunt.com',
  },

  searchHints: [
    'What are you craving today?',
    'Search for chicken wings…',
    'Explore our burgers…',
    'Looking for desserts?',
    'Find your favorite bowl…',
    'Try our crispy sides…',
  ],
};
